# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Mon Aug 24 23:34:14 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 480)
        MainWindow.setMinimumSize(QtCore.QSize(450, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HorizLayout_RootName = QtWidgets.QHBoxLayout()
        self.HorizLayout_RootName.setObjectName("HorizLayout_RootName")
        self.Label_RootName = QtWidgets.QLabel(self.centralwidget)
        self.Label_RootName.setEnabled(True)
        self.Label_RootName.setMaximumSize(QtCore.QSize(154, 16777215))
        self.Label_RootName.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_RootName.setObjectName("Label_RootName")
        self.HorizLayout_RootName.addWidget(self.Label_RootName)
        self.lineEdit_RootName = QtWidgets.QLabel(self.centralwidget)
        self.lineEdit_RootName.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(100, 100, 100);")
        self.lineEdit_RootName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_RootName.setObjectName("lineEdit_RootName")
        self.HorizLayout_RootName.addWidget(self.lineEdit_RootName)
        self.pushButt_RootName_GetSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_RootName_GetSel.setMaximumSize(QtCore.QSize(110, 16777215))
        self.pushButt_RootName_GetSel.setObjectName("pushButt_RootName_GetSel")
        self.HorizLayout_RootName.addWidget(self.pushButt_RootName_GetSel)
        self.verticalLayout.addLayout(self.HorizLayout_RootName)
        self.HorizLayout_fileName = QtWidgets.QHBoxLayout()
        self.HorizLayout_fileName.setObjectName("HorizLayout_fileName")
        self.checkBox_fileName = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_fileName.setFont(font)
        self.checkBox_fileName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_fileName.setObjectName("checkBox_fileName")
        self.HorizLayout_fileName.addWidget(self.checkBox_fileName)
        self.lineEdit_fileName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fileName.setEnabled(False)
        self.lineEdit_fileName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_fileName.setObjectName("lineEdit_fileName")
        self.HorizLayout_fileName.addWidget(self.lineEdit_fileName)
        self.verticalLayout.addLayout(self.HorizLayout_fileName)
        self.gridLayout_ComAss = QtWidgets.QGridLayout()
        self.gridLayout_ComAss.setObjectName("gridLayout_ComAss")
        self.pushButt_Com_List = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_Com_List.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButt_Com_List.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButt_Com_List.setObjectName("pushButt_Com_List")
        self.gridLayout_ComAss.addWidget(self.pushButt_Com_List, 2, 3, 1, 1)
        self.pushButt_Com_DelSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_Com_DelSel.setMinimumSize(QtCore.QSize(35, 0))
        self.pushButt_Com_DelSel.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButt_Com_DelSel.setObjectName("pushButt_Com_DelSel")
        self.gridLayout_ComAss.addWidget(self.pushButt_Com_DelSel, 2, 6, 1, 1)
        self.Label_Ass = QtWidgets.QLabel(self.centralwidget)
        self.Label_Ass.setEnabled(True)
        self.Label_Ass.setObjectName("Label_Ass")
        self.gridLayout_ComAss.addWidget(self.Label_Ass, 0, 1, 1, 1)
        self.pushButt_Ass_DelSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_Ass_DelSel.setMinimumSize(QtCore.QSize(35, 0))
        self.pushButt_Ass_DelSel.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButt_Ass_DelSel.setObjectName("pushButt_Ass_DelSel")
        self.gridLayout_ComAss.addWidget(self.pushButt_Ass_DelSel, 0, 6, 1, 1)
        self.pushButt_Ass_AddSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_Ass_AddSel.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButt_Ass_AddSel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButt_Ass_AddSel.setObjectName("pushButt_Ass_AddSel")
        self.gridLayout_ComAss.addWidget(self.pushButt_Ass_AddSel, 0, 4, 1, 1)
        self.Label_Com = QtWidgets.QLabel(self.centralwidget)
        self.Label_Com.setEnabled(True)
        self.Label_Com.setObjectName("Label_Com")
        self.gridLayout_ComAss.addWidget(self.Label_Com, 2, 1, 1, 1)
        self.lineEdit_Ass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Ass.setEnabled(True)
        self.lineEdit_Ass.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_Ass.setObjectName("lineEdit_Ass")
        self.gridLayout_ComAss.addWidget(self.lineEdit_Ass, 0, 2, 1, 1)
        self.pushButt_Ass_List = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_Ass_List.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButt_Ass_List.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButt_Ass_List.setObjectName("pushButt_Ass_List")
        self.gridLayout_ComAss.addWidget(self.pushButt_Ass_List, 0, 3, 1, 1)
        self.pushButt_Ass_GetSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_Ass_GetSel.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButt_Ass_GetSel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButt_Ass_GetSel.setObjectName("pushButt_Ass_GetSel")
        self.gridLayout_ComAss.addWidget(self.pushButt_Ass_GetSel, 0, 5, 1, 1)
        self.pushButt_Com_GetSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_Com_GetSel.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButt_Com_GetSel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButt_Com_GetSel.setObjectName("pushButt_Com_GetSel")
        self.gridLayout_ComAss.addWidget(self.pushButt_Com_GetSel, 2, 5, 1, 1)
        self.pushButt_Com_AddSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_Com_AddSel.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButt_Com_AddSel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButt_Com_AddSel.setObjectName("pushButt_Com_AddSel")
        self.gridLayout_ComAss.addWidget(self.pushButt_Com_AddSel, 2, 4, 1, 1)
        self.lineEdit_Com = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Com.setEnabled(True)
        self.lineEdit_Com.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_Com.setObjectName("lineEdit_Com")
        self.gridLayout_ComAss.addWidget(self.lineEdit_Com, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_ComAss)
        self.horizLayout_proxy = QtWidgets.QHBoxLayout()
        self.horizLayout_proxy.setObjectName("horizLayout_proxy")
        self.checkBox_cleanAttr = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_cleanAttr.setFont(font)
        self.checkBox_cleanAttr.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_cleanAttr.setChecked(True)
        self.checkBox_cleanAttr.setObjectName("checkBox_cleanAttr")
        self.horizLayout_proxy.addWidget(self.checkBox_cleanAttr)
        self.line_Space_proxy_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_Space_proxy_1.setMinimumSize(QtCore.QSize(10, 0))
        self.line_Space_proxy_1.setLineWidth(0)
        self.line_Space_proxy_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_Space_proxy_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_Space_proxy_1.setObjectName("line_Space_proxy_1")
        self.horizLayout_proxy.addWidget(self.line_Space_proxy_1)
        self.checkBox_proxy = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_proxy.setFont(font)
        self.checkBox_proxy.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_proxy.setObjectName("checkBox_proxy")
        self.horizLayout_proxy.addWidget(self.checkBox_proxy)
        self.line_Space_proxy_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_Space_proxy_2.setMinimumSize(QtCore.QSize(10, 0))
        self.line_Space_proxy_2.setLineWidth(0)
        self.line_Space_proxy_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_Space_proxy_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_Space_proxy_2.setObjectName("line_Space_proxy_2")
        self.horizLayout_proxy.addWidget(self.line_Space_proxy_2)
        self.label_proxy = QtWidgets.QLabel(self.centralwidget)
        self.label_proxy.setEnabled(False)
        self.label_proxy.setObjectName("label_proxy")
        self.horizLayout_proxy.addWidget(self.label_proxy)
        self.lineEdit_proxy = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_proxy.setEnabled(False)
        self.lineEdit_proxy.setObjectName("lineEdit_proxy")
        self.horizLayout_proxy.addWidget(self.lineEdit_proxy)
        self.pushButt_proxy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButt_proxy.setEnabled(False)
        self.pushButt_proxy.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButt_proxy.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButt_proxy.setObjectName("pushButt_proxy")
        self.horizLayout_proxy.addWidget(self.pushButt_proxy)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizLayout_proxy.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizLayout_proxy)
        self.horizLayout_ABCOption = QtWidgets.QHBoxLayout()
        self.horizLayout_ABCOption.setObjectName("horizLayout_ABCOption")
        self.gridLayout_ABCOption = QtWidgets.QGridLayout()
        self.gridLayout_ABCOption.setObjectName("gridLayout_ABCOption")
        self.checkBox_WriteVisibility = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_WriteVisibility.setObjectName("checkBox_WriteVisibility")
        self.gridLayout_ABCOption.addWidget(self.checkBox_WriteVisibility, 5, 2, 1, 1)
        self.checkBox_WritsUvSets = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_WritsUvSets.setChecked(True)
        self.checkBox_WritsUvSets.setObjectName("checkBox_WritsUvSets")
        self.gridLayout_ABCOption.addWidget(self.checkBox_WritsUvSets, 1, 3, 1, 1)
        self.checkBox_WriteCreases = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_WriteCreases.setEnabled(True)
        self.checkBox_WriteCreases.setObjectName("checkBox_WriteCreases")
        self.gridLayout_ABCOption.addWidget(self.checkBox_WriteCreases, 6, 2, 1, 1)
        self.checkBox_RenderableOnly = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_RenderableOnly.setObjectName("checkBox_RenderableOnly")
        self.gridLayout_ABCOption.addWidget(self.checkBox_RenderableOnly, 2, 3, 1, 1)
        self.checkBox_FilterEulerRotations = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_FilterEulerRotations.setObjectName("checkBox_FilterEulerRotations")
        self.gridLayout_ABCOption.addWidget(self.checkBox_FilterEulerRotations, 5, 3, 1, 1)
        self.checkBox_WorldSpace = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_WorldSpace.setChecked(True)
        self.checkBox_WorldSpace.setObjectName("checkBox_WorldSpace")
        self.gridLayout_ABCOption.addWidget(self.checkBox_WorldSpace, 0, 3, 1, 1)
        self.checkBox_WriteColorSets = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_WriteColorSets.setObjectName("checkBox_WriteColorSets")
        self.gridLayout_ABCOption.addWidget(self.checkBox_WriteColorSets, 3, 3, 1, 1)
        self.checkBox_NoNormals = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_NoNormals.setObjectName("checkBox_NoNormals")
        self.gridLayout_ABCOption.addWidget(self.checkBox_NoNormals, 1, 2, 1, 1)
        self.label_ABCOption = QtWidgets.QLabel(self.centralwidget)
        self.label_ABCOption.setObjectName("label_ABCOption")
        self.gridLayout_ABCOption.addWidget(self.label_ABCOption, 0, 0, 1, 1)
        self.checkBox_UVWrite = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_UVWrite.setChecked(True)
        self.checkBox_UVWrite.setObjectName("checkBox_UVWrite")
        self.gridLayout_ABCOption.addWidget(self.checkBox_UVWrite, 0, 2, 1, 1)
        self.checkBox_WriteFaceSets = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_WriteFaceSets.setObjectName("checkBox_WriteFaceSets")
        self.gridLayout_ABCOption.addWidget(self.checkBox_WriteFaceSets, 4, 2, 1, 1)
        self.checkBox_Verbose = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Verbose.setObjectName("checkBox_Verbose")
        self.gridLayout_ABCOption.addWidget(self.checkBox_Verbose, 2, 2, 1, 1)
        self.line_Space_ABCOption = QtWidgets.QFrame(self.centralwidget)
        self.line_Space_ABCOption.setMinimumSize(QtCore.QSize(30, 0))
        self.line_Space_ABCOption.setLineWidth(0)
        self.line_Space_ABCOption.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_Space_ABCOption.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_Space_ABCOption.setObjectName("line_Space_ABCOption")
        self.gridLayout_ABCOption.addWidget(self.line_Space_ABCOption, 0, 1, 1, 1)
        self.checkBox_StripNamespaces = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_StripNamespaces.setObjectName("checkBox_StripNamespaces")
        self.gridLayout_ABCOption.addWidget(self.checkBox_StripNamespaces, 3, 2, 1, 1)
        self.checkBox_WholeFrameGeo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_WholeFrameGeo.setObjectName("checkBox_WholeFrameGeo")
        self.gridLayout_ABCOption.addWidget(self.checkBox_WholeFrameGeo, 4, 3, 1, 1)
        self.checkBox_extra = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_extra.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_extra.setStyleSheet(":indicator{width: 0px;}")
        self.checkBox_extra.setCheckable(False)
        self.checkBox_extra.setObjectName("checkBox_extra")
        self.gridLayout_ABCOption.addWidget(self.checkBox_extra, 1, 0, 1, 1)
        self.toolButton_extra = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_extra.setMaximumSize(QtCore.QSize(30, 16777215))
        self.toolButton_extra.setStyleSheet("QToolButton { border: none; }")
        self.toolButton_extra.setCheckable(True)
        self.toolButton_extra.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_extra.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_extra.setObjectName("toolButton_extra")
        self.gridLayout_ABCOption.addWidget(self.toolButton_extra, 1, 1, 1, 1)
        self.horizLayout_ABCOption.addLayout(self.gridLayout_ABCOption)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizLayout_ABCOption.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizLayout_ABCOption)
        self.HorizLayout_arbAtt = QtWidgets.QHBoxLayout()
        self.HorizLayout_arbAtt.setObjectName("HorizLayout_arbAtt")
        self.checkBox_arbAtt = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_arbAtt.setFont(font)
        self.checkBox_arbAtt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_arbAtt.setObjectName("checkBox_arbAtt")
        self.HorizLayout_arbAtt.addWidget(self.checkBox_arbAtt)
        self.Line_arbAtt = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_arbAtt.setEnabled(False)
        self.Line_arbAtt.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Line_arbAtt.setAlignment(QtCore.Qt.AlignCenter)
        self.Line_arbAtt.setObjectName("Line_arbAtt")
        self.HorizLayout_arbAtt.addWidget(self.Line_arbAtt)
        self.verticalLayout.addLayout(self.HorizLayout_arbAtt)
        self.horizLayout_Ani = QtWidgets.QHBoxLayout()
        self.horizLayout_Ani.setObjectName("horizLayout_Ani")
        self.checkBox_Ani = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Ani.setFont(font)
        self.checkBox_Ani.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_Ani.setObjectName("checkBox_Ani")
        self.horizLayout_Ani.addWidget(self.checkBox_Ani)
        self.line_Ani_Space1 = QtWidgets.QFrame(self.centralwidget)
        self.line_Ani_Space1.setMinimumSize(QtCore.QSize(20, 0))
        self.line_Ani_Space1.setLineWidth(0)
        self.line_Ani_Space1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_Ani_Space1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_Ani_Space1.setObjectName("line_Ani_Space1")
        self.horizLayout_Ani.addWidget(self.line_Ani_Space1)
        self.label_Ani_Start = QtWidgets.QLabel(self.centralwidget)
        self.label_Ani_Start.setEnabled(False)
        self.label_Ani_Start.setObjectName("label_Ani_Start")
        self.horizLayout_Ani.addWidget(self.label_Ani_Start)
        self.spinBox_Ani_Start = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Ani_Start.setEnabled(False)
        self.spinBox_Ani_Start.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_Ani_Start.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_Ani_Start.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_Ani_Start.setObjectName("spinBox_Ani_Start")
        self.horizLayout_Ani.addWidget(self.spinBox_Ani_Start)
        self.line_Ani_Space2 = QtWidgets.QFrame(self.centralwidget)
        self.line_Ani_Space2.setMinimumSize(QtCore.QSize(10, 0))
        self.line_Ani_Space2.setLineWidth(0)
        self.line_Ani_Space2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_Ani_Space2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_Ani_Space2.setObjectName("line_Ani_Space2")
        self.horizLayout_Ani.addWidget(self.line_Ani_Space2)
        self.label_Ani_End = QtWidgets.QLabel(self.centralwidget)
        self.label_Ani_End.setEnabled(False)
        self.label_Ani_End.setObjectName("label_Ani_End")
        self.horizLayout_Ani.addWidget(self.label_Ani_End)
        self.spinBox_Ani_End = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Ani_End.setEnabled(False)
        self.spinBox_Ani_End.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_Ani_End.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_Ani_End.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_Ani_End.setObjectName("spinBox_Ani_End")
        self.horizLayout_Ani.addWidget(self.spinBox_Ani_End)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizLayout_Ani.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizLayout_Ani)
        self.HorizLayout_Path = QtWidgets.QHBoxLayout()
        self.HorizLayout_Path.setObjectName("HorizLayout_Path")
        self.Label_Path = QtWidgets.QLabel(self.centralwidget)
        self.Label_Path.setEnabled(True)
        self.Label_Path.setObjectName("Label_Path")
        self.HorizLayout_Path.addWidget(self.Label_Path)
        self.Line_Path = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Path.setEnabled(True)
        self.Line_Path.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Line_Path.setAlignment(QtCore.Qt.AlignCenter)
        self.Line_Path.setObjectName("Line_Path")
        self.HorizLayout_Path.addWidget(self.Line_Path)
        self.Button_Path = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Path.setObjectName("Button_Path")
        self.HorizLayout_Path.addWidget(self.Button_Path)
        self.verticalLayout.addLayout(self.HorizLayout_Path)
        self.Button_Export = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Export.setMinimumSize(QtCore.QSize(0, 30))
        self.Button_Export.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Button_Export.setObjectName("Button_Export")
        self.verticalLayout.addWidget(self.Button_Export)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 23))
        self.menubar.setObjectName("menubar")
        self.menu_Options = QtWidgets.QMenu(self.menubar)
        self.menu_Options.setObjectName("menu_Options")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.action_Reset = QtWidgets.QAction(MainWindow)
        self.action_Reset.setObjectName("action_Reset")
        self.action_Help = QtWidgets.QAction(MainWindow)
        self.action_Help.setObjectName("action_Help")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menu_Options.addAction(self.action_Help)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.checkBox_arbAtt, QtCore.SIGNAL("clicked(bool)"), self.Line_arbAtt.setEnabled)
        QtCore.QObject.connect(self.checkBox_Ani, QtCore.SIGNAL("clicked(bool)"), self.spinBox_Ani_Start.setEnabled)
        QtCore.QObject.connect(self.checkBox_Ani, QtCore.SIGNAL("clicked(bool)"), self.spinBox_Ani_End.setEnabled)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_Verbose.setVisible)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_RenderableOnly.setVisible)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_StripNamespaces.setVisible)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_WriteColorSets.setVisible)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_WriteFaceSets.setVisible)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_WholeFrameGeo.setVisible)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_WriteVisibility.setVisible)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_FilterEulerRotations.setVisible)
        QtCore.QObject.connect(self.toolButton_extra, QtCore.SIGNAL("clicked(bool)"), self.checkBox_WriteCreases.setVisible)
        QtCore.QObject.connect(self.checkBox_extra, QtCore.SIGNAL("clicked()"), self.toolButton_extra.click)
        QtCore.QObject.connect(self.checkBox_Ani, QtCore.SIGNAL("clicked(bool)"), self.label_Ani_Start.setEnabled)
        QtCore.QObject.connect(self.checkBox_Ani, QtCore.SIGNAL("clicked(bool)"), self.label_Ani_End.setEnabled)
        QtCore.QObject.connect(self.checkBox_proxy, QtCore.SIGNAL("clicked(bool)"), self.pushButt_proxy.setEnabled)
        QtCore.QObject.connect(self.checkBox_proxy, QtCore.SIGNAL("clicked(bool)"), self.label_proxy.setEnabled)
        QtCore.QObject.connect(self.checkBox_proxy, QtCore.SIGNAL("clicked(bool)"), self.lineEdit_proxy.setEnabled)
        QtCore.QObject.connect(self.checkBox_fileName, QtCore.SIGNAL("clicked(bool)"), self.lineEdit_fileName.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButt_RootName_GetSel, self.lineEdit_Com)
        MainWindow.setTabOrder(self.lineEdit_Com, self.pushButt_Com_List)
        MainWindow.setTabOrder(self.pushButt_Com_List, self.pushButt_Com_AddSel)
        MainWindow.setTabOrder(self.pushButt_Com_AddSel, self.pushButt_Com_GetSel)
        MainWindow.setTabOrder(self.pushButt_Com_GetSel, self.Line_Path)
        MainWindow.setTabOrder(self.Line_Path, self.Button_Path)
        MainWindow.setTabOrder(self.Button_Path, self.Button_Export)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "ExportScenegraphXML", None, -1))
        self.Label_RootName.setText(QtWidgets.QApplication.translate("MainWindow", "File Name And Root Model", None, -1))
        self.lineEdit_RootName.setText(QtWidgets.QApplication.translate("MainWindow", "Root_Model", None, -1))
        self.pushButt_RootName_GetSel.setText(QtWidgets.QApplication.translate("MainWindow", "Get Selection", None, -1))
        self.checkBox_fileName.setText(QtWidgets.QApplication.translate("MainWindow", "File Name", None, -1))
        self.lineEdit_fileName.setText(QtWidgets.QApplication.translate("MainWindow", "file_name.xml", None, -1))
        self.pushButt_Com_List.setText(QtWidgets.QApplication.translate("MainWindow", "List", None, -1))
        self.pushButt_Com_DelSel.setText(QtWidgets.QApplication.translate("MainWindow", "Del", None, -1))
        self.Label_Ass.setText(QtWidgets.QApplication.translate("MainWindow", "Assembly", None, -1))
        self.pushButt_Ass_DelSel.setText(QtWidgets.QApplication.translate("MainWindow", "Del", None, -1))
        self.pushButt_Ass_AddSel.setText(QtWidgets.QApplication.translate("MainWindow", "Add Sel", None, -1))
        self.Label_Com.setText(QtWidgets.QApplication.translate("MainWindow", "Component", None, -1))
        self.lineEdit_Ass.setText(QtWidgets.QApplication.translate("MainWindow", "optional", None, -1))
        self.pushButt_Ass_List.setText(QtWidgets.QApplication.translate("MainWindow", "List", None, -1))
        self.pushButt_Ass_GetSel.setText(QtWidgets.QApplication.translate("MainWindow", "Get Sel", None, -1))
        self.pushButt_Com_GetSel.setText(QtWidgets.QApplication.translate("MainWindow", "Get Sel", None, -1))
        self.pushButt_Com_AddSel.setText(QtWidgets.QApplication.translate("MainWindow", "Add Sel", None, -1))
        self.checkBox_cleanAttr.setText(QtWidgets.QApplication.translate("MainWindow", "Clean Attr", None, -1))
        self.checkBox_proxy.setText(QtWidgets.QApplication.translate("MainWindow", "Proxy", None, -1))
        self.label_proxy.setText(QtWidgets.QApplication.translate("MainWindow", "Postfix", None, -1))
        self.lineEdit_proxy.setText(QtWidgets.QApplication.translate("MainWindow", "_proxy", None, -1))
        self.pushButt_proxy.setText(QtWidgets.QApplication.translate("MainWindow", "Pick Postfix", None, -1))
        self.checkBox_WriteVisibility.setText(QtWidgets.QApplication.translate("MainWindow", "Write Visibility", None, -1))
        self.checkBox_WritsUvSets.setText(QtWidgets.QApplication.translate("MainWindow", "Writs UV Sets", None, -1))
        self.checkBox_WriteCreases.setText(QtWidgets.QApplication.translate("MainWindow", "Write Creases", None, -1))
        self.checkBox_RenderableOnly.setText(QtWidgets.QApplication.translate("MainWindow", "Renderable Only", None, -1))
        self.checkBox_FilterEulerRotations.setText(QtWidgets.QApplication.translate("MainWindow", "Filter Euler Rotations", None, -1))
        self.checkBox_WorldSpace.setText(QtWidgets.QApplication.translate("MainWindow", "World Space", None, -1))
        self.checkBox_WriteColorSets.setText(QtWidgets.QApplication.translate("MainWindow", "Write Color Sets", None, -1))
        self.checkBox_NoNormals.setText(QtWidgets.QApplication.translate("MainWindow", "No Normals", None, -1))
        self.label_ABCOption.setText(QtWidgets.QApplication.translate("MainWindow", "Alembic Options", None, -1))
        self.checkBox_UVWrite.setText(QtWidgets.QApplication.translate("MainWindow", "UV Write", None, -1))
        self.checkBox_WriteFaceSets.setText(QtWidgets.QApplication.translate("MainWindow", "Write Face Sets", None, -1))
        self.checkBox_Verbose.setText(QtWidgets.QApplication.translate("MainWindow", "Verbose", None, -1))
        self.checkBox_StripNamespaces.setText(QtWidgets.QApplication.translate("MainWindow", "Strip Namespaces", None, -1))
        self.checkBox_WholeFrameGeo.setText(QtWidgets.QApplication.translate("MainWindow", "Whole Frame Geo", None, -1))
        self.checkBox_extra.setText(QtWidgets.QApplication.translate("MainWindow", "Extra", None, -1))
        self.checkBox_arbAtt.setText(QtWidgets.QApplication.translate("MainWindow", "arbAttrs", None, -1))
        self.Line_arbAtt.setText(QtWidgets.QApplication.translate("MainWindow", "optional", None, -1))
        self.checkBox_Ani.setText(QtWidgets.QApplication.translate("MainWindow", "Animation", None, -1))
        self.label_Ani_Start.setText(QtWidgets.QApplication.translate("MainWindow", "Start Frame", None, -1))
        self.label_Ani_End.setText(QtWidgets.QApplication.translate("MainWindow", "End Frame", None, -1))
        self.Label_Path.setText(QtWidgets.QApplication.translate("MainWindow", "Export Path", None, -1))
        self.Line_Path.setText(QtWidgets.QApplication.translate("MainWindow", "Path", None, -1))
        self.Button_Path.setText(QtWidgets.QApplication.translate("MainWindow", "Set Path", None, -1))
        self.Button_Export.setText(QtWidgets.QApplication.translate("MainWindow", "Export", None, -1))
        self.menu_Options.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.action_Reset.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.action_Help.setText(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))

